#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-Angular
Version  : 1.3.18.1
Release  : 14
URL      : https://pypi.python.org/packages/source/X/XStatic-Angular/XStatic-Angular-1.3.18.1.tar.gz
Source0  : https://pypi.python.org/packages/source/X/XStatic-Angular/XStatic-Angular-1.3.18.1.tar.gz
Summary  : Angular 1.3.18 (XStatic packaging standard)
Group    : Development/Tools
License  : MIT MPL-2.0
Requires: XStatic-Angular-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
XStatic-Angular
---------------
Angular JavaScript library packaged for setuptools (easy_install) / pip.

%package python
Summary: python components for the XStatic-Angular package.
Group: Default
Provides: xstatic-angular-python

%description python
python components for the XStatic-Angular package.


%prep
cd ..
%setup -q -n XStatic-Angular-1.3.18.1

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
