#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-Angular
Version  : 1.4.10.1
Release  : 17
URL      : http://pypi.debian.net/XStatic-Angular/XStatic-Angular-1.4.10.1.tar.gz
Source0  : http://pypi.debian.net/XStatic-Angular/XStatic-Angular-1.4.10.1.tar.gz
Summary  : XStatic-Angular
Group    : Development/Tools
License  : MIT MPL-2.0
Requires: XStatic-Angular-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : setuptools
BuildRequires : setuptools_scm
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : wheel

%description
XStatic-Angular
---------------
Angular JavaScript library packaged for setuptools (easy_install) / pip.

%package python
Summary: python components for the XStatic-Angular package.
Group: Default
Provides: xstatic-angular-python

%description python
python components for the XStatic-Angular package.


%prep
%setup -q -n XStatic-Angular-1.4.10.1

%build
export LANG=C
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
%exclude /usr/lib/python2.7/site-packages/xstatic/__init__.py
%exclude /usr/lib/python2.7/site-packages/xstatic/__init__.pyc
%exclude /usr/lib/python2.7/site-packages/xstatic/pkg/__init__.py
%exclude /usr/lib/python2.7/site-packages/xstatic/pkg/__init__.pyc
/usr/lib/python*/*
