#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-Angular
Version  : 1.3.7.0
Release  : 9
URL      : https://pypi.python.org/packages/source/X/XStatic-Angular/XStatic-Angular-1.3.7.0.tar.gz
Source0  : https://pypi.python.org/packages/source/X/XStatic-Angular/XStatic-Angular-1.3.7.0.tar.gz
Summary  : Angular 1.3.7 (XStatic packaging standard)
Group    : Development/Tools
License  : MIT MPL-2.0
Requires: XStatic-Angular-python
BuildRequires : python-dev
BuildRequires : setuptools

%description
XStatic-Angular
---------------
Angular JavaScript library packaged for setuptools (easy_install) / pip.

%package python
Summary: python components for the XStatic-Angular package.
Group: Default

%description python
python components for the XStatic-Angular package.


%prep
%setup -q -n XStatic-Angular-1.3.7.0

%build
%{__python} setup.py build

%install
rm -rf %{buildroot}
%{__python} setup.py install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
